### 1. 회원가입
POST http://localhost/member/join
Content-Type: application/json

{
  "id": "kimname",
  "pass" : "testtest",
  "name" : "김이름",
  "phone" : "010-1234-1234"
}


### 2. 로그인
POST http://localhost/member/login
Content-Type: application/json

{
  "id": "kimname",
  "pass" : "testtest"
}
